name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: 64200002@kmitl.ac.th
        password: IDmain0980169099

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: your-dockerhub-username/costmanagement:latest
